-- Tighten the builds.user_id FK from ON DELETE SET NULL to ON DELETE CASCADE.
--
-- Codex security review-4 finding: with SET NULL, deleting a Clerk user
-- (via the user.deleted webhook) silently reverts every build they had
-- claimed back to user_id IS NULL — i.e. anonymous, mutable by anyone
-- with the slug. That re-exposed the build's edit surface and broke the
-- ownership guarantee a signed-in user thought they had.
--
-- Cascading instead means "delete account = delete the builds you saved".
-- That matches the typical SaaS expectation and removes the re-anonymize
-- vector entirely. build_items already CASCADEs from builds.id, so this
-- chain is clean. affiliate_clicks keeps its ON DELETE SET NULL on
-- buildId for analytics retention — that one is intentional.
--
-- Constraint name is auto-generated by postgres on creation, so we
-- discover it dynamically and re-create with the new policy.
DO $$
DECLARE
    con_name text;
BEGIN
    SELECT con.conname INTO con_name
    FROM pg_constraint con
    JOIN pg_class cls ON cls.oid = con.conrelid
    JOIN pg_namespace nsp ON nsp.oid = cls.relnamespace
    WHERE cls.relname = 'builds'
      AND nsp.nspname = current_schema()
      AND con.contype = 'f'
      AND EXISTS (
          SELECT 1 FROM unnest(con.conkey) ck
          JOIN pg_attribute att ON att.attrelid = cls.oid AND att.attnum = ck
          WHERE att.attname = 'user_id'
      );
    IF con_name IS NOT NULL THEN
        EXECUTE format('ALTER TABLE builds DROP CONSTRAINT %I', con_name);
    END IF;
END $$;
--> statement-breakpoint

ALTER TABLE "builds"
    ADD CONSTRAINT "builds_user_id_users_id_fk"
    FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE;
